### ISSUE TITLE
Design Docs To Do List - Wiki, Features, Schema, and Sample State

### ISSUE THREAD

**Issue by mwmadsen67** [danielliem49/Pathfinder#1]
Hi Daniel, here is checklist for going through your docs. I'll go through what you have so far and leave comments underneath. 

---

# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

---

# Feature List

- [x] Should have 7 Features.
    - [x] 3 of those are User Auth, render.io, and Production README.
    - [x] The other 4 are from the [Feature/MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each feature
- [x] Correctly formatted
    - [x] features are listed in an ordered list
    - [x] Each feature is broken down into bullet points

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by mwmadsen67** [comment]
Hey I'm going to leave some comments on what you have so far:

Feature List:
- It's up to you, but I think parks and trails should be done concurrently, since they're so tightly linked together. Like a park page is kind of a trail index page, for example. I would plan on trails having a park_id, and in that way, it would make sense to build out parks first. Other than that, your feature list looks good.

Schema:
- users looks good
- for trails, it all looks good except the park_id should not be unique
- reviews do not need a photo_id - the way photos will work is through something called active storage, which will create its own table that you'll create associations with. because of that you will also not need a photos table

That's all I have for you for now, nice work so far! Let me know if you have any questions

**Comment by mwmadsen67** [comment]
Sample State:
- Trails will need key for photoUrls, which will contain an array of photo urls for that trail. Using active storage, each trail will "have many" photos, which you'll grab in your jbuilder on a trail show request.
- otherwise looks good.

**Comment by mwmadsen67** [comment]
just kidding you also need a session slice of state and an errors slice of state, at the same level as entities, then youre good

**Comment by mwmadsen67** [comment]
Also, I'm looking at your schema again and you shouldn't need a photos table. When you set up active storage it will create its own tables, but you dont need to list the stuff that active storage creates here. It might seem a bit confusing now but there is a whole video series and reading explaining how to use it once you get to that.

**Comment by cjc473** [comment]
Complete!
