### ISSUE TITLE
Design Docs - Backend and Frontend Routes

### ISSUE THREAD

**Issue by mwmadsen67** [danielliem49/Pathfinder#2]
# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain superfluous routes
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by mwmadsen67** [comment]
Backend Routes:
- a backend route for return a specific user's information should be a show route, like `GET /api/users/:id`
- I wouldn't include a patch users route since that isnt currently a planned feature. updating a user is not a requirement of user auth
- for reviews, you dont need a reviews index route. When you load up a trail on a trail show page you will be able to grab a bunch of associated information in the jbuilder file, including associated reviews. Since there is no individual review index page, you shouldn't need this route.
- you do need to include routes for creating, updating, and deleting reviews
- you do not need a route for photos, photos will always be a part of any trail fetches.

Frontend Routes:
- looks good

**Comment by cjc473** [comment]
Complete!
